#include "../Input/GraphicsAPIInput.h"

namespace dooms
{
	namespace input
	{
		namespace GraphicsAPIInput
		{
			DOOMS_ENGINE_GRAPHICS_API GRAPHICS_INITIALIZEGRAPHICSAPIINPUT InitializeGraphisAPIInput;
			DOOMS_ENGINE_GRAPHICS_API GRAPHICS_DEINITIALIZEGRAPHICSAPIINPUT DeInitializeGraphisAPIInput;
			DOOMS_ENGINE_GRAPHICS_API GRAPHICS_POLLEVENTS PollEvents;
			DOOMS_ENGINE_GRAPHICS_API GRAPHICS_SETCURSORMODE SetCursorMode;
			DOOMS_ENGINE_GRAPHICS_API GRAPHICS_SETCURSORENTERCALLBACK SetCursorEnterCallback;
			DOOMS_ENGINE_GRAPHICS_API GRAPHICS_SETCURSORPOSITIONCALLBACK SetCursorPosition_Callback;
			DOOMS_ENGINE_GRAPHICS_API GRAPHICS_SETSCROLLCALLBACK SetScroll_Callback;
			DOOMS_ENGINE_GRAPHICS_API GRAPHICS_SETKEYCALLBACK SetKey_Callback;
			DOOMS_ENGINE_GRAPHICS_API GRAPHICS_SETMOUSEBUTTONCALLBACK SetMouseButton_Callback;
		}
	}
}