#include "shaderReflectionDataParser.h"

#include <nlohmann/json.hpp>

// Parse reflection data contained in json file generated by https://github.com/septag/glslcc
dooms::asset::shaderReflectionDataParser::ShaderReflectionData dooms::asset::shaderReflectionDataParser::ParseShaderReflectionStringText
(
	const std::string& reflectionDataJsonText
)
{
	ShaderReflectionData shaderReflectionData;

	return shaderReflectionData;
}
