#include "shaderReflectionDataParser.h"

#include <nlohmann/json.hpp>

void dooms::asset::shaderReflectionDataParser::ShaderReflectionData::Clear()
{
	mIsGenerated = false;
	mTargetGraphicsAPIType = dooms::graphics::GraphicsAPI::eGraphicsAPIType::GraphicsAPIType_NONE;
	mShaderVersion.clear();
	ShaderReflectionDataFileName.clear();
	mShaderType = dooms::graphics::GraphicsAPI::eGraphicsPipeLineStage::DUMMY;
	mInputVariables.clear();
	mOutputVariables.clear();
	mUniformBuffers.clear();
}

// Parse reflection data contained in json file generated by https://github.com/septag/glslcc
dooms::asset::shaderReflectionDataParser::ShaderReflectionData dooms::asset::shaderReflectionDataParser::ParseShaderReflectionStringText
(
	const std::string& reflectionDataJsonText
)
{
	ShaderReflectionData shaderReflectionData;

	return shaderReflectionData;
}
