#pragma once

#include <Core.h>


#ifdef D_DEBUG_CPU_VENDOR_PROFILER

#include <AMDProfileController.h>

#ifndef CPU_VENDOR_PROFILER_RESUME
#define CPU_VENDOR_PROFILER_RESUME amdProfileResume(AMD_PROFILE_CPU)
#endif


#ifndef CPU_VENDOR_PROFILER_PAUSE
#define CPU_VENDOR_PROFILER_PAUSE amdProfilePause(AMD_PROFILE_CPU)
#endif


#ifndef PROFILING_WITH_CPU_VENDOR_PROFILER	

#define PROFILING_WITH_CPU_VENDOR_PROFILER(FUNCTION)		\
			CPU_VENDOR_PROFILER_RESUME;						\
			FUNCTION;										\
			CPU_VENDOR_PROFILER_RESUME;						\

#endif

#ifndef CONDITIONAL_PROFILING_WITH_CPU_VENDOR_PROFILER	

#define CONDITIONAL_PROFILING_WITH_CPU_VENDOR_PROFILER(CONDITION, FUNCTION)		\
			if (CONDITION)														\
			{																	\
				PROFILING_WITH_CPU_VENDOR_PROFILER(FUNCTION)					\
			}																	\
			else																\
			{																	\
				EXIT_PROGRAM;														\
			}																	\

#endif

#else


#ifndef CPU_VENDOR_PROFILER_RESUME
#define CPU_VENDOR_PROFILER_RESUME
#endif

#ifndef CPU_VENDOR_PROFILER_PAUSE
#define CPU_VENDOR_PROFILER_PAUSE
#endif


#ifndef PROFILING_WITH_CPU_VENDOR_PROFILER	
#define PROFILING_WITH_CPU_VENDOR_PROFILER
#endif

#ifndef CONDITIONAL_PROFILING_WITH_CPU_VENDOR_PROFILER	
#define CONDITIONAL_PROFILING_WITH_CPU_VENDOR_PROFILER
#endif

#endif